name: ${project.name}
main:  ${groupId}.${project.name}
version: ${project.version}
url: ${project.url}
author: andune
database: false
commands:
  sak:
    description: SwissArmyKnife admin command
    permission: sak.admin
permissions:
    sak.*:
        description: Gives access to all plugin permissions
        children:
            sak.admin: true
    sak.admin:
        description: Allows access to admin functions
        default: op
